/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    FiveSection: typeof import('./components/FiveSection.vue')['default']
    FourSection: typeof import('./components/FourSection.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NewsSection: typeof import('./components/NewsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondSection: typeof import('./components/SecondSection.vue')['default']
    SixSection: typeof import('./components/SixSection.vue')['default']
    ThirdSection: typeof import('./components/ThirdSection.vue')['default']
    TitleSection: typeof import('./components/TitleSection.vue')['default']
  }
}
